//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlvdesStoreDBEntities : DbContext
    {
        public BlvdesStoreDBEntities()
            : base("name=BlvdesStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Carts> Carts { get; set; }
        public DbSet<CSSkins> CSSkins { get; set; }
        public DbSet<DotaHeroes> DotaHeroes { get; set; }
        public DbSet<DotaRarities> DotaRarities { get; set; }
        public DbSet<DotaSkins> DotaSkins { get; set; }
        public DbSet<DotaSlots> DotaSlots { get; set; }
        public DbSet<FilterCS> FilterCS { get; set; }
        public DbSet<Games> Games { get; set; }
        public DbSet<HoldPeriods> HoldPeriods { get; set; }
        public DbSet<Inventory> Inventory { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<SubcategoryCS> SubcategoryCS { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Transactions> Transactions { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
