//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSSkins
    {
        public int SkinId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> SubcategoryId { get; set; }
        public Nullable<int> HoldPeriodId { get; set; }
        public Nullable<int> GameId { get; set; }
    
        public virtual SubcategoryCS SubcategoryCS { get; set; }
        public virtual FilterCS FilterCS { get; set; }
        public virtual Games Games { get; set; }
        public virtual HoldPeriods HoldPeriods { get; set; }
    }
}
