//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotaSlots
    {
        public DotaSlots()
        {
            this.DotaSkins = new HashSet<DotaSkins>();
        }
    
        public int SlotId { get; set; }
        public string SlotName { get; set; }
    
        public virtual ICollection<DotaSkins> DotaSkins { get; set; }
    }
}
