//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotaSkins
    {
        public int SkinId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> HeroId { get; set; }
        public Nullable<int> SlotId { get; set; }
        public Nullable<int> RarityId { get; set; }
        public Nullable<int> HoldPeriodId { get; set; }
        public Nullable<int> GameId { get; set; }
    
        public virtual DotaHeroes DotaHeroes { get; set; }
        public virtual DotaRarities DotaRarities { get; set; }
        public virtual DotaSlots DotaSlots { get; set; }
        public virtual Games Games { get; set; }
        public virtual HoldPeriods HoldPeriods { get; set; }
    }
}
