//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilterCS
    {
        public FilterCS()
        {
            this.CSSkins = new HashSet<CSSkins>();
            this.SubcategoryCS = new HashSet<SubcategoryCS>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<CSSkins> CSSkins { get; set; }
        public virtual ICollection<SubcategoryCS> SubcategoryCS { get; set; }
    }
}
