//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Carts = new HashSet<Carts>();
            this.CSSkins = new HashSet<CSSkins>();
            this.DotaSkins = new HashSet<DotaSkins>();
            this.Inventory = new HashSet<Inventory>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int GameId { get; set; }
        public string GameName { get; set; }
    
        public virtual ICollection<Carts> Carts { get; set; }
        public virtual ICollection<CSSkins> CSSkins { get; set; }
        public virtual ICollection<DotaSkins> DotaSkins { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
