//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoldPeriods
    {
        public HoldPeriods()
        {
            this.CSSkins = new HashSet<CSSkins>();
            this.DotaSkins = new HashSet<DotaSkins>();
        }
    
        public int HoldPeriodId { get; set; }
        public Nullable<int> HoldDays { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CSSkins> CSSkins { get; set; }
        public virtual ICollection<DotaSkins> DotaSkins { get; set; }
    }
}
