//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubcategoryCS
    {
        public SubcategoryCS()
        {
            this.CSSkins = new HashSet<CSSkins>();
        }
    
        public int SubcategoryId { get; set; }
        public string SubcategoryName { get; set; }
        public Nullable<int> TypeId { get; set; }
    
        public virtual ICollection<CSSkins> CSSkins { get; set; }
        public virtual FilterCS FilterCS { get; set; }
    }
}
