//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KURSOVAYA_RABOTA.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Carts = new HashSet<Carts>();
            this.Inventory = new HashSet<Inventory>();
            this.Orders = new HashSet<Orders>();
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string NickName { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public byte[] AvatarImage { get; set; }
    
        public virtual ICollection<Carts> Carts { get; set; }
        public virtual ICollection<Inventory> Inventory { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Transactions> Transactions { get; set; }
    }
}
